### ISSUE TITLE
Vimeo error

### ISSUE THREAD

**Issue by Wykeless** [lem6ns/firerip#2]
Hello, im getting this:

ERROR: [vimeo] 773633416:

    at Function.YTDlpWrap.createError (....\firerip\node_modules\yt-dlp-wrap\dist\index.js:346:16)
    at ChildProcess.<anonymous> (...\firerip\node_modules\yt-dlp-wrap\dist\index.js:173:58)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    
yt-dlp version 2023.01.06 latest version as of writing this

**Comment by lem6ns** [comment]
[#1 ](https://github.com/lem6ns/firerip/issues/1#issuecomment-1363685973)
